# Первоначальная настройка окружения для работы с проектом.
init: envsetup

# Установка зависимостей
envsetup:
	python3.8 -m pip install -r requirements.txt

# Запуск приложения рест-апи
run:
	python3.8 src/main.py
